### ISSUE TITLE
Ask about landmark detection encode

### ISSUE THREAD

**Issue by hksonngan** [lab-midas/med_segmentation#13]
Hi Thomas,
Thank you for your code.
As I check the code has the model for landmark detection ([body identification](https://github.com/lab-midas/med_segmentation/blob/master/models/ModelSet.py#L627)).
I want to apply this for cardiac (AV, Apex, Aorta root, mitral valve, left/right coronary)
but I don't know how to encode for above code? (is encoded as a mask or as X, Y, Z position?)

Thanks,
Tran

**Comment by thomaskuestner** [comment]
The landmark detection implemented in this framework is not suited for this task. It only serves the purpose to mark body regions in a 2D coronal view.
