### ISSUE TITLE
Which model in ModelSet.py is the DCNet model

### ISSUE THREAD

**Issue by dmus** [lab-midas/med_segmentation#14]
Hi, thanks for sharing this work. I cloned this repository and read the paper "Fully automated and standardized segmentation of adipose tissue compartments via deep learning in 3D whole-body MRI of epidemiological cohort studies". Now I am wondering which of the models in ModelSet.py are used in the paper. Which one corresponds to the proposed DCNet and which one corresponds to the reference UNet?

**Comment by thomaskuestner** [comment]
Hi, the models used in the paper are a combination of MRGE and DCNet which in the implemented framework is the "premodel_MRGE". The reference UNet model is denoted as "premodel_UNet". You can check the config files in `config/pretrained_model` to see the various parametrizations for the conducted experiments in the paper.
