### ISSUE TITLE
Error when trying to run example

### ISSUE THREAD

**Issue by karllandheer** [lab-midas/med_segmentation#16]
Hello, when I try to run this line: python3 main.py --preprocess -c config/config_default.yml I get the error 

sage: MedSeg [-h] [-e EXP_NAME] [--preprocess PREPROCESS] [--train TRAIN] [--evaluate EVALUATE] [--predict PREDICT] [--restore RESTORE] [-c CONFIG_PATH] [--gpu GPU]
              [--gpu_memory GPU_MEMORY] [--calculate_max_shape_only CALCULATE_MAX_SHAPE_ONLY] [--split_only SPLIT_ONLY] [--train_epoch TRAIN_EPOCH] [--filters FILTERS]
              [--model_name MODEL_NAME] [--train_batch TRAIN_BATCH] [--dataset DATASET]
MedSeg: error: argument --preprocess: expected one argument

Any idea what is going on?

**Comment by thomaskuestner** [comment]
Thanks for pointing this out. This should be fixed by 5b36be3d7ff1dd1092846b3482977f97353f5d2e
