### ISSUE TITLE
sort slice location have problem with my dataset

### ISSUE THREAD

**Issue by hksonngan** [lab-midas/med_segmentation#28]
Hi Thomas,
I don't know why sorted function doesn't work for my dataset as it starts from negative

sorted(dicom_paths, key=lambda dicom_path: [pydicom.dcmread(dicom_path).SliceLocation)](https://github.com/lab-midas/med_segmentation/blob/master/med_io/read_dicom.py#L41)

So I try by use numpy argsort as below.
```python
    slicelocation = np.zeros(len(dicom_paths))
    # sort as slice location
    for f, i in zip(dicom_paths, range(len(dicom_paths))):
        ds = pydicom.read_file(f)
        if('slicelocation' in ds):	slicelocation[i] = ds.SliceLocation
        else:	slicelocation[i] = ds.ImagePositionPatient[2]
    order = np.argsort(slicelocation)
    dicom_paths= np.array(dicom_paths)[order]

```

**Comment by hksonngan** [comment]
close as I don't think big issue

**Comment by thomaskuestner** [comment]
ok, maybe vendor- and sequence-dependent tag that can require custom handling
