### ISSUE TITLE
Missing get_fixed_patches_index in pipeline.py

### ISSUE THREAD

**Issue by hksonngan** [lab-midas/med_segmentation#9]
Hi,
I try to run but get the error with missing function get_fixed_patches_index.
As I check pipeline.py and get_pad_and_patch.py is idendical.
Thanks.
Tran

**Comment by thomaskuestner** [comment]
Hi Tran,
thanks for pointing that out. This was accidentally copied over. I rolled it back to the original version. This should be solved in https://github.com/lab-midas/med_segmentation/commit/5d3aa05b42cb3dfbd2305d4b47548c7ed611b880 
Kind regards
Thomas
